# grabl config
# @graknlabs_grakn_core

config:
  version-candidate: ./VERSION
  dependencies:
    - graql: [snapshot, release]
    - protocol: [snapshot, release]
    - client-java: release

sync:
  validation:
    jobs:
      sync-validate-compilation:
        machine: ubuntu-19.10
        type: foreground
        script: |
          bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_DEPENDENCIES_NEW         # graql@abc123 protocol@bcd234
          bazel build //...
      sync-validate-correctness:
        machine: ubuntu-19.10
        type: foreground
        script: |
          bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_DEPENDENCIES_NEW         # graql@abc123 protocol@bcd234
          bazel build //test/basic-correctness
    execution:
      - sync-validate-compilation
      - sync-validate-correctness
  update:
    job:
      machine: ubuntu-19.10
      type: foreground
      script: |
        bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_DEPENDENCIES_NEW         # graql@abc123 protocol@bcd234
        bazel run @graknlabs_build_tools//sync-dependencies-npm $GRABL_DEPENDENCIES_NEW           # graql@abc123 protocol@bcd234
        # Committing and pushing to the upstream repo should be done by Grabl

build:
  static-analysis:
    job:
      dependency-analysis:
        machine: ubuntu-19.10
        type: foreground
        script: bazel run @graknlabs_build_tools//analysis:dependency -- graql@graknlabs_graql protocol@graknlabs_protocol client-java@graknlabs_client_java
        # export $GRABL_DEPENDENCIES_STATUS="graql@123,protocol@234,client-java@345"
        # grabl.io/events/automation/graknlabs/grakn/edbea56/build/static-anlaysis/dependency -- graql@123, protocol@234, client-java@345
  performance:
    jobs:
      run-grakn-1:
        machine: ubuntu-19.10
        type: background
        script: |
          # bazel build //:grakn-core-all-linux-targz
          # tar -xf ./bazel-bin/grakn-core-all-linux.targz -C ./dist/
          # cd ./dist/
          # ./grakn server start
          echo 'run-grakn-1'
      run-grakn-2:
        machine: ubuntu-19.10
        type: background
        script: |
          # bazel build //:grakn-core-all-linux-targz
          # tar -xf ./bazel-bin/grakn-core-all-linux.targz -C ./dist/
          # ./grakn server start join $GRABL_PERFORMANCE_RUN_GRAKN_1_ADDRESS
          echo 'run-grakn-2'
      run-grakn-3:
        machine: ubuntu-19.10
        type: background
        script: |
          # bazel build //:grakn-core-all-linux-targz
          # tar -xf ./bazel-bin/grakn-core-all-linux.targz -C ./dist/
          # cd ./dist/
          # ./grakn server start join $GRABL_PERFORMANCE_RUN_GRAKN_1_ADDRESS
          echo 'run-grakn-3'
      test-performance-big:
        machine: ubuntu-19.10
        type: foreground
        script: |
          # bazel test //test/performance:big --
          #   --grakn-address $GRABL_PERFORMANCE_RUN_GRAKN_1_ADDRESS
          #   --org $GRABL_ORG
          #   --repo $GRABL_REPO
          #   --commit $GRABL_COMMIT
          #   --username $GRABL_USERNAME
          #   --token $GRABL_TOKEN
          echo 'test-performance-big'
    execution:
      - run-grakn-1
      - run-grakn-2:
          depends: [run-grakn-1]
      - run-grakn-3:
          depends: [run-grakn-1]
      - test-performance-big:
          depends: [run-grakn-1, run-grakn-2, run-grakn-3]

release:
  validation:
    job:
      machine: ubuntu-19.10
      type: foreground
      script: |
        bazel run @graknlabs_build_tools//ci:release-validate-deps -- graknlabs_common graknlabs_graql graknlabs_protocol
  deployment:
    jobs:
    execution:
  bump:
    job:
      machine: ubuntu-19.10
      type: foreground
      script: bazel run @graknlabs_build_tools//ci:version-bump
